# frozen_string_literal: true

source ENV['GEM_SOURCE'] || 'https://rubygems.org'

gem 'openbolt',             ENV['RUBYGEM_OPENBOLT']

# CVE fixes

# Older fixes have been updated in the 3.2 minor releases:

# https://github.com/ruby/ruby/releases/tag/v3_2_11
# https://github.com/ruby/ruby/releases/tag/v3_2_10
# https://github.com/ruby/ruby/releases/tag/v3_2_9
# https://github.com/ruby/ruby/releases/tag/v3_2_8
# https://github.com/ruby/ruby/releases/tag/v3_2_7
# https://github.com/ruby/ruby/releases/tag/v3_2_6
# https://github.com/ruby/ruby/releases/tag/v3_2_5
# https://github.com/ruby/ruby/releases/tag/v3_2_4
# https://github.com/ruby/ruby/releases/tag/v3_2_3
# https://github.com/ruby/ruby/releases/tag/v3_2_2
# https://github.com/ruby/ruby/releases/tag/v3_2_1

gem 'net-imap', '>= 0.6.4'
gem 'erb',      '>= 6.0.4'
